add rest api
YuriyZanin/go-rest-api-homework pull request #1
Opened 2023-11-30 10:05 UTC by YuriyZanin

sprint #6

2023-12-04 11:55 UTC, robotomize requested changes
Хорошая работа, но есть пара фиксов

2023-12-04 11:55 UTC, robotomize commented on precode.go
> +	r.Get("/task/{id}", getTask)
Ошибка в указании пути до ресурса. В данном случае у нас ресурс task но обращаемся к ним во множественном числе /tasks это просто унификация restful

2023-12-04 11:55 UTC, robotomize commented on precode.go
> +		http.Error(w, "Задача не найдена", http.StatusNoContent)
В данном случае авторы задания в целом хотят вернть тут StatusBadRquest. 
Коротко о вашем стататусе, если не по заданию делать сюда больше подходит статус http.StatusNotFound, а http.StatusNoContent применяется чаще всего, когда мы отправляем, какой-нибудь post запрос на осуществление действия и ответ не предполагается.

2023-12-04 11:55 UTC, robotomize commented on precode.go
> +	w.Write(resp)
w.Write может возвращать ошибку

2023-12-04 18:09 UTC, YuriyZanin commented on precode.go
> +	r.Get("/task/{id}", getTask)
унифицировал пути

2023-12-04 18:10 UTC, YuriyZanin commented on precode.go
> +		http.Error(w, "Задача не найдена", http.StatusNoContent)
переделал на bad request

2023-12-04 18:50 UTC, YuriyZanin commented on precode.go
> +	w.Write(resp)
добавил проверку на ошибку

2023-12-04 19:08 UTC, robotomize approved these changes
Не забывайте закрыть Body в добавлении таска. Добавьте после ревью. В остальном отлично, принимается!

2023-12-04 19:08 UTC, robotomize commented on precode.go
> +	}
Не забывайте закрывать Body

2023-12-04 19:08 UTC, robotomize commented on precode.go
> +	_, err := buf.ReadFrom(r.Body)
В данном случае вы сделали корректно, но можно чуть упростить, например используя пакет io.ReadAll (править не обязательно)

2023-12-05 05:40 UTC, YuriyZanin commented on precode.go
> +	}
добавил defer

2023-12-05 05:41 UTC, merged